/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SitemapYearIndexRouteImport } from './routes/sitemap.$year.index'
import { Route as SitemapYearMonthRouteImport } from './routes/sitemap.$year.$month'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapYearIndexRoute = SitemapYearIndexRouteImport.update({
  id: '/sitemap/$year/',
  path: '/sitemap/$year/',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapYearMonthRoute = SitemapYearMonthRouteImport.update({
  id: '/sitemap/$year/$month',
  path: '/sitemap/$year/$month',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/search': typeof SearchRoute
  '/sitemap/$year/$month': typeof SitemapYearMonthRoute
  '/sitemap/$year/': typeof SitemapYearIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/search': typeof SearchRoute
  '/sitemap/$year/$month': typeof SitemapYearMonthRoute
  '/sitemap/$year': typeof SitemapYearIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/search': typeof SearchRoute
  '/sitemap/$year/$month': typeof SitemapYearMonthRoute
  '/sitemap/$year/': typeof SitemapYearIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/search' | '/sitemap/$year/$month' | '/sitemap/$year/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/search' | '/sitemap/$year/$month' | '/sitemap/$year'
  id: '__root__' | '/' | '/search' | '/sitemap/$year/$month' | '/sitemap/$year/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SearchRoute: typeof SearchRoute
  SitemapYearMonthRoute: typeof SitemapYearMonthRoute
  SitemapYearIndexRoute: typeof SitemapYearIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap/$year/': {
      id: '/sitemap/$year/'
      path: '/sitemap/$year'
      fullPath: '/sitemap/$year/'
      preLoaderRoute: typeof SitemapYearIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap/$year/$month': {
      id: '/sitemap/$year/$month'
      path: '/sitemap/$year/$month'
      fullPath: '/sitemap/$year/$month'
      preLoaderRoute: typeof SitemapYearMonthRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SearchRoute: SearchRoute,
  SitemapYearMonthRoute: SitemapYearMonthRoute,
  SitemapYearIndexRoute: SitemapYearIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
