/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SitemapYearRouteImport } from './routes/sitemap.$year'
import { Route as SitemapYearMonthRouteImport } from './routes/sitemap.$year.$month'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapYearRoute = SitemapYearRouteImport.update({
  id: '/sitemap/$year',
  path: '/sitemap/$year',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapYearMonthRoute = SitemapYearMonthRouteImport.update({
  id: '/$month',
  path: '/$month',
  getParentRoute: () => SitemapYearRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sitemap/$year': typeof SitemapYearRouteWithChildren
  '/sitemap/$year/$month': typeof SitemapYearMonthRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sitemap/$year': typeof SitemapYearRouteWithChildren
  '/sitemap/$year/$month': typeof SitemapYearMonthRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sitemap/$year': typeof SitemapYearRouteWithChildren
  '/sitemap/$year/$month': typeof SitemapYearMonthRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/sitemap/$year' | '/sitemap/$year/$month'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/sitemap/$year' | '/sitemap/$year/$month'
  id: '__root__' | '/' | '/sitemap/$year' | '/sitemap/$year/$month'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SitemapYearRoute: typeof SitemapYearRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap/$year': {
      id: '/sitemap/$year'
      path: '/sitemap/$year'
      fullPath: '/sitemap/$year'
      preLoaderRoute: typeof SitemapYearRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap/$year/$month': {
      id: '/sitemap/$year/$month'
      path: '/$month'
      fullPath: '/sitemap/$year/$month'
      preLoaderRoute: typeof SitemapYearMonthRouteImport
      parentRoute: typeof SitemapYearRoute
    }
  }
}

interface SitemapYearRouteChildren {
  SitemapYearMonthRoute: typeof SitemapYearMonthRoute
}

const SitemapYearRouteChildren: SitemapYearRouteChildren = {
  SitemapYearMonthRoute: SitemapYearMonthRoute,
}

const SitemapYearRouteWithChildren = SitemapYearRoute._addFileChildren(
  SitemapYearRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SitemapYearRoute: SitemapYearRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
